// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: maping/v1/maping.proto

// Package maping.v1 is the mAPI-ng ingest wire contract.
//
// This schema is a PUBLIC, STABLE contract: the client library is open source
// (MIT, ADR-0004), so third parties may build against it. Evolve it
// backward-compatibly only — `buf breaking` is enforced in CI from commit 1.
// The DDSketch bucket layout (gamma/offset) is frozen and versioned by
// sketch_format_version; see ADR-0001 and ADR-0003.
package mapingv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/arhuman/maping/proto/maping/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngestServiceName is the fully-qualified name of the IngestService service.
	IngestServiceName = "maping.v1.IngestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngestServiceRegisterProcedure is the fully-qualified name of the IngestService's Register RPC.
	IngestServiceRegisterProcedure = "/maping.v1.IngestService/Register"
	// IngestServiceUploadProcedure is the fully-qualified name of the IngestService's Upload RPC.
	IngestServiceUploadProcedure = "/maping.v1.IngestService/Upload"
)

// IngestServiceClient is a client for the maping.v1.IngestService service.
type IngestServiceClient interface {
	Register(context.Context, *connect.Request[v1.Handshake]) (*connect.Response[v1.RegisterResponse], error)
	Upload(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error)
}

// NewIngestServiceClient constructs a client for the maping.v1.IngestService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingestServiceMethods := v1.File_maping_v1_maping_proto.Services().ByName("IngestService").Methods()
	return &ingestServiceClient{
		register: connect.NewClient[v1.Handshake, v1.RegisterResponse](
			httpClient,
			baseURL+IngestServiceRegisterProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		upload: connect.NewClient[v1.UploadRequest, v1.UploadResponse](
			httpClient,
			baseURL+IngestServiceUploadProcedure,
			connect.WithSchema(ingestServiceMethods.ByName("Upload")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingestServiceClient implements IngestServiceClient.
type ingestServiceClient struct {
	register *connect.Client[v1.Handshake, v1.RegisterResponse]
	upload   *connect.Client[v1.UploadRequest, v1.UploadResponse]
}

// Register calls maping.v1.IngestService.Register.
func (c *ingestServiceClient) Register(ctx context.Context, req *connect.Request[v1.Handshake]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Upload calls maping.v1.IngestService.Upload.
func (c *ingestServiceClient) Upload(ctx context.Context, req *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error) {
	return c.upload.CallUnary(ctx, req)
}

// IngestServiceHandler is an implementation of the maping.v1.IngestService service.
type IngestServiceHandler interface {
	Register(context.Context, *connect.Request[v1.Handshake]) (*connect.Response[v1.RegisterResponse], error)
	Upload(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error)
}

// NewIngestServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngestServiceHandler(svc IngestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingestServiceMethods := v1.File_maping_v1_maping_proto.Services().ByName("IngestService").Methods()
	ingestServiceRegisterHandler := connect.NewUnaryHandler(
		IngestServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(ingestServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	ingestServiceUploadHandler := connect.NewUnaryHandler(
		IngestServiceUploadProcedure,
		svc.Upload,
		connect.WithSchema(ingestServiceMethods.ByName("Upload")),
		connect.WithHandlerOptions(opts...),
	)
	return "/maping.v1.IngestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngestServiceRegisterProcedure:
			ingestServiceRegisterHandler.ServeHTTP(w, r)
		case IngestServiceUploadProcedure:
			ingestServiceUploadHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngestServiceHandler struct{}

func (UnimplementedIngestServiceHandler) Register(context.Context, *connect.Request[v1.Handshake]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("maping.v1.IngestService.Register is not implemented"))
}

func (UnimplementedIngestServiceHandler) Upload(context.Context, *connect.Request[v1.UploadRequest]) (*connect.Response[v1.UploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("maping.v1.IngestService.Upload is not implemented"))
}
