// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: maping/v1/maping.proto

// Package maping.v1 is the mAPI-ng ingest wire contract.
//
// This schema is a PUBLIC, STABLE contract: the client library is open source
// (MIT, ADR-0004), so third parties may build against it. Evolve it
// backward-compatibly only — `buf breaking` is enforced in CI from commit 1.
// The DDSketch bucket layout (gamma/offset) is frozen and versioned by
// sketch_format_version; see ADR-0001 and ADR-0003.

package mapingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusClass is the HTTP status bucket used as a series-key dimension.
// Exact codes live in Summary.status_code_breakdown, never as a series label.
type StatusClass int32

const (
	// STATUS_CLASS_UNSPECIFIED must never be sent; it guards proto3 default-zero.
	StatusClass_STATUS_CLASS_UNSPECIFIED StatusClass = 0
	StatusClass_STATUS_CLASS_2XX         StatusClass = 1
	StatusClass_STATUS_CLASS_3XX         StatusClass = 2
	StatusClass_STATUS_CLASS_4XX         StatusClass = 3
	StatusClass_STATUS_CLASS_5XX         StatusClass = 4
	// STATUS_CLASS_NO_STATUS covers write-timeouts / requests aborted before a
	// status was written. Counted as an error, tracked separately (docs/context.md).
	StatusClass_STATUS_CLASS_NO_STATUS StatusClass = 5
)

// Enum value maps for StatusClass.
var (
	StatusClass_name = map[int32]string{
		0: "STATUS_CLASS_UNSPECIFIED",
		1: "STATUS_CLASS_2XX",
		2: "STATUS_CLASS_3XX",
		3: "STATUS_CLASS_4XX",
		4: "STATUS_CLASS_5XX",
		5: "STATUS_CLASS_NO_STATUS",
	}
	StatusClass_value = map[string]int32{
		"STATUS_CLASS_UNSPECIFIED": 0,
		"STATUS_CLASS_2XX":         1,
		"STATUS_CLASS_3XX":         2,
		"STATUS_CLASS_4XX":         3,
		"STATUS_CLASS_5XX":         4,
		"STATUS_CLASS_NO_STATUS":   5,
	}
)

func (x StatusClass) Enum() *StatusClass {
	p := new(StatusClass)
	*p = x
	return p
}

func (x StatusClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusClass) Descriptor() protoreflect.EnumDescriptor {
	return file_maping_v1_maping_proto_enumTypes[0].Descriptor()
}

func (StatusClass) Type() protoreflect.EnumType {
	return &file_maping_v1_maping_proto_enumTypes[0]
}

func (x StatusClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusClass.Descriptor instead.
func (StatusClass) EnumDescriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{0}
}

// Envelope carries source identity and is sent once per upload batch.
type Envelope struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Service    string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                         // logical app name (auto-derived)
	Instance   string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`                       // replica id (auto-derived)
	SdkVersion string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"` // client SDK version, for compat handling
	// sketch_format_version identifies the DDSketch bucket layout so the server
	// can reject sketches it cannot interpret rather than corrupt percentiles.
	SketchFormatVersion uint32 `protobuf:"varint,4,opt,name=sketch_format_version,json=sketchFormatVersion,proto3" json:"sketch_format_version,omitempty"`
	// dropped_summaries counts Summaries dropped by client backpressure since the
	// last successful upload, so the gap is visible rather than silent.
	DroppedSummaries uint64 `protobuf:"varint,5,opt,name=dropped_summaries,json=droppedSummaries,proto3" json:"dropped_summaries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_maping_v1_maping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Envelope) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Envelope) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Envelope) GetSketchFormatVersion() uint32 {
	if x != nil {
		return x.SketchFormatVersion
	}
	return 0
}

func (x *Envelope) GetDroppedSummaries() uint64 {
	if x != nil {
		return x.DroppedSummaries
	}
	return 0
}

// Summary is one client-side aggregate for a single (endpoint, status-class)
// over one flush window. It is the unit of data mAPI-ng ships (no per-request
// events in v1).
type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowStartMs int64                  `protobuf:"varint,1,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"` // client wall clock, window start
	WindowEndMs   int64                  `protobuf:"varint,2,opt,name=window_end_ms,json=windowEndMs,proto3" json:"window_end_ms,omitempty"`       // client wall clock, window end
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`                                       // HTTP method
	RouteTemplate string                 `protobuf:"bytes,4,opt,name=route_template,json=routeTemplate,proto3" json:"route_template,omitempty"`    // registered route template, never raw path
	StatusClass   StatusClass            `protobuf:"varint,5,opt,name=status_class,json=statusClass,proto3,enum=maping.v1.StatusClass" json:"status_class,omitempty"`
	Count         uint64                 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`                                        // requests in window (gives rate)
	SumDurationNs uint64                 `protobuf:"varint,7,opt,name=sum_duration_ns,json=sumDurationNs,proto3" json:"sum_duration_ns,omitempty"` // for an exact mean alongside sketch percentiles
	ReqBytes      uint64                 `protobuf:"varint,8,opt,name=req_bytes,json=reqBytes,proto3" json:"req_bytes,omitempty"`                  // summed request bytes (bandwidth per endpoint)
	RespBytes     uint64                 `protobuf:"varint,9,opt,name=resp_bytes,json=respBytes,proto3" json:"resp_bytes,omitempty"`               // summed response bytes
	// latency_sketch is a DDSketch as a sparse bucket-index -> count map.
	// Keys are int32 to match server storage (Map(Int32,UInt64)) and avoid a
	// future migration. Interpreted per Envelope.sketch_format_version.
	LatencySketch map[int32]uint64 `protobuf:"bytes,10,rep,name=latency_sketch,json=latencySketch,proto3" json:"latency_sketch,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// status_code_breakdown is the exact-code detail (bounded, top-N) for the
	// endpoint-detail view. Not a series-key dimension.
	StatusCodeBreakdown map[uint32]uint64 `protobuf:"bytes,11,rep,name=status_code_breakdown,json=statusCodeBreakdown,proto3" json:"status_code_breakdown,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_maping_v1_maping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{1}
}

func (x *Summary) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *Summary) GetWindowEndMs() int64 {
	if x != nil {
		return x.WindowEndMs
	}
	return 0
}

func (x *Summary) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Summary) GetRouteTemplate() string {
	if x != nil {
		return x.RouteTemplate
	}
	return ""
}

func (x *Summary) GetStatusClass() StatusClass {
	if x != nil {
		return x.StatusClass
	}
	return StatusClass_STATUS_CLASS_UNSPECIFIED
}

func (x *Summary) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Summary) GetSumDurationNs() uint64 {
	if x != nil {
		return x.SumDurationNs
	}
	return 0
}

func (x *Summary) GetReqBytes() uint64 {
	if x != nil {
		return x.ReqBytes
	}
	return 0
}

func (x *Summary) GetRespBytes() uint64 {
	if x != nil {
		return x.RespBytes
	}
	return 0
}

func (x *Summary) GetLatencySketch() map[int32]uint64 {
	if x != nil {
		return x.LatencySketch
	}
	return nil
}

func (x *Summary) GetStatusCodeBreakdown() map[uint32]uint64 {
	if x != nil {
		return x.StatusCodeBreakdown
	}
	return nil
}

// UploadRequest is one batched, fire-and-forget upload.
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Summaries     []*Summary             `protobuf:"bytes,2,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_maping_v1_maping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *UploadRequest) GetSummaries() []*Summary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is false when the whole batch was rejected (e.g. bad key handled
	// at the transport layer); reason carries a machine-readable code the client
	// logs (rate-limited) and surfaces in the dashboard.
	Accepted bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// rejected_summaries reports partial drops (e.g. cardinality frozen) so the
	// client can log the count without failing the whole upload.
	RejectedSummaries uint64 `protobuf:"varint,3,opt,name=rejected_summaries,json=rejectedSummaries,proto3" json:"rejected_summaries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_maping_v1_maping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UploadResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UploadResponse) GetRejectedSummaries() uint64 {
	if x != nil {
		return x.RejectedSummaries
	}
	return 0
}

// Handshake is a one-time registration ping sent on recorder startup. It proves
// auth + connectivity before any traffic and drives the dashboard onboarding
// state. It is not a metric. (Named for the domain concept, not
// RegisterRequest — see the RPC_REQUEST_STANDARD_NAME lint exception in
// buf.yaml.)
type Handshake struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Service             string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Instance            string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	SdkVersion          string                 `protobuf:"bytes,3,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	SketchFormatVersion uint32                 `protobuf:"varint,4,opt,name=sketch_format_version,json=sketchFormatVersion,proto3" json:"sketch_format_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_maping_v1_maping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{4}
}

func (x *Handshake) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Handshake) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Handshake) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *Handshake) GetSketchFormatVersion() uint32 {
	if x != nil {
		return x.SketchFormatVersion
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_maping_v1_maping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_maping_v1_maping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_maping_v1_maping_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_maping_v1_maping_proto protoreflect.FileDescriptor

const file_maping_v1_maping_proto_rawDesc = "" +
	"\n" +
	"\x16maping/v1/maping.proto\x12\tmaping.v1\"\xc2\x01\n" +
	"\bEnvelope\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x122\n" +
	"\x15sketch_format_version\x18\x04 \x01(\rR\x13sketchFormatVersion\x12+\n" +
	"\x11dropped_summaries\x18\x05 \x01(\x04R\x10droppedSummaries\"\x82\x05\n" +
	"\aSummary\x12&\n" +
	"\x0fwindow_start_ms\x18\x01 \x01(\x03R\rwindowStartMs\x12\"\n" +
	"\rwindow_end_ms\x18\x02 \x01(\x03R\vwindowEndMs\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12%\n" +
	"\x0eroute_template\x18\x04 \x01(\tR\rrouteTemplate\x129\n" +
	"\fstatus_class\x18\x05 \x01(\x0e2\x16.maping.v1.StatusClassR\vstatusClass\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x04R\x05count\x12&\n" +
	"\x0fsum_duration_ns\x18\a \x01(\x04R\rsumDurationNs\x12\x1b\n" +
	"\treq_bytes\x18\b \x01(\x04R\breqBytes\x12\x1d\n" +
	"\n" +
	"resp_bytes\x18\t \x01(\x04R\trespBytes\x12L\n" +
	"\x0elatency_sketch\x18\n" +
	" \x03(\v2%.maping.v1.Summary.LatencySketchEntryR\rlatencySketch\x12_\n" +
	"\x15status_code_breakdown\x18\v \x03(\v2+.maping.v1.Summary.StatusCodeBreakdownEntryR\x13statusCodeBreakdown\x1a@\n" +
	"\x12LatencySketchEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aF\n" +
	"\x18StatusCodeBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"r\n" +
	"\rUploadRequest\x12/\n" +
	"\benvelope\x18\x01 \x01(\v2\x13.maping.v1.EnvelopeR\benvelope\x120\n" +
	"\tsummaries\x18\x02 \x03(\v2\x12.maping.v1.SummaryR\tsummaries\"s\n" +
	"\x0eUploadResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x12rejected_summaries\x18\x03 \x01(\x04R\x11rejectedSummaries\"\x96\x01\n" +
	"\tHandshake\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1f\n" +
	"\vsdk_version\x18\x03 \x01(\tR\n" +
	"sdkVersion\x122\n" +
	"\x15sketch_format_version\x18\x04 \x01(\rR\x13sketchFormatVersion\"F\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x9f\x01\n" +
	"\vStatusClass\x12\x1c\n" +
	"\x18STATUS_CLASS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_CLASS_2XX\x10\x01\x12\x14\n" +
	"\x10STATUS_CLASS_3XX\x10\x02\x12\x14\n" +
	"\x10STATUS_CLASS_4XX\x10\x03\x12\x14\n" +
	"\x10STATUS_CLASS_5XX\x10\x04\x12\x1a\n" +
	"\x16STATUS_CLASS_NO_STATUS\x10\x052\x8d\x01\n" +
	"\rIngestService\x12=\n" +
	"\bRegister\x12\x14.maping.v1.Handshake\x1a\x1b.maping.v1.RegisterResponse\x12=\n" +
	"\x06Upload\x12\x18.maping.v1.UploadRequest\x1a\x19.maping.v1.UploadResponseB4Z2github.com/arhuman/maping/proto/maping/v1;mapingv1b\x06proto3"

var (
	file_maping_v1_maping_proto_rawDescOnce sync.Once
	file_maping_v1_maping_proto_rawDescData []byte
)

func file_maping_v1_maping_proto_rawDescGZIP() []byte {
	file_maping_v1_maping_proto_rawDescOnce.Do(func() {
		file_maping_v1_maping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maping_v1_maping_proto_rawDesc), len(file_maping_v1_maping_proto_rawDesc)))
	})
	return file_maping_v1_maping_proto_rawDescData
}

var file_maping_v1_maping_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_maping_v1_maping_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_maping_v1_maping_proto_goTypes = []any{
	(StatusClass)(0),         // 0: maping.v1.StatusClass
	(*Envelope)(nil),         // 1: maping.v1.Envelope
	(*Summary)(nil),          // 2: maping.v1.Summary
	(*UploadRequest)(nil),    // 3: maping.v1.UploadRequest
	(*UploadResponse)(nil),   // 4: maping.v1.UploadResponse
	(*Handshake)(nil),        // 5: maping.v1.Handshake
	(*RegisterResponse)(nil), // 6: maping.v1.RegisterResponse
	nil,                      // 7: maping.v1.Summary.LatencySketchEntry
	nil,                      // 8: maping.v1.Summary.StatusCodeBreakdownEntry
}
var file_maping_v1_maping_proto_depIdxs = []int32{
	0, // 0: maping.v1.Summary.status_class:type_name -> maping.v1.StatusClass
	7, // 1: maping.v1.Summary.latency_sketch:type_name -> maping.v1.Summary.LatencySketchEntry
	8, // 2: maping.v1.Summary.status_code_breakdown:type_name -> maping.v1.Summary.StatusCodeBreakdownEntry
	1, // 3: maping.v1.UploadRequest.envelope:type_name -> maping.v1.Envelope
	2, // 4: maping.v1.UploadRequest.summaries:type_name -> maping.v1.Summary
	5, // 5: maping.v1.IngestService.Register:input_type -> maping.v1.Handshake
	3, // 6: maping.v1.IngestService.Upload:input_type -> maping.v1.UploadRequest
	6, // 7: maping.v1.IngestService.Register:output_type -> maping.v1.RegisterResponse
	4, // 8: maping.v1.IngestService.Upload:output_type -> maping.v1.UploadResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_maping_v1_maping_proto_init() }
func file_maping_v1_maping_proto_init() {
	if File_maping_v1_maping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maping_v1_maping_proto_rawDesc), len(file_maping_v1_maping_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maping_v1_maping_proto_goTypes,
		DependencyIndexes: file_maping_v1_maping_proto_depIdxs,
		EnumInfos:         file_maping_v1_maping_proto_enumTypes,
		MessageInfos:      file_maping_v1_maping_proto_msgTypes,
	}.Build()
	File_maping_v1_maping_proto = out.File
	file_maping_v1_maping_proto_goTypes = nil
	file_maping_v1_maping_proto_depIdxs = nil
}
